const test=require('node:test'),assert=require('node:assert/strict'),ExcelJS=require('exceljs');
const {createPayrollWorkbook}=require('../services/payrollExcelService');
const rows=[
 {employee_code:'NV0004',employee_name:'Nguyễn Công Hào',job_grade:'assistant',employee_type:'official',working_days:25,standard_days:26,revenue_amount:10000000,productivity_salary:0,base_salary:5000000,meal_allowance:600000,fuel_allowance:0,phone_allowance:0,allowance:600000,bonus:100000,deduction:200000,advance_total:500000,paid_total:1000000,net_salary:5500000,balance_due:4000000,status:'pending_payment'},
 {employee_code:'NV0005',employee_name:'Nguyễn Văn B',job_grade:'technician',employee_type:'official',working_days:26,standard_days:26,revenue_amount:45000000,productivity_salary:12000000,base_salary:5000000,meal_allowance:600000,fuel_allowance:1000000,phone_allowance:300000,allowance:1900000,bonus:0,deduction:0,advance_total:0,paid_total:0,net_salary:13900000,balance_due:13900000,status:'created'}
];
test('professional payroll workbook has two styled sheets and selected period',async()=>{const workbook=await createPayrollWorkbook(rows,{month:8,year:2026});assert.deepEqual(workbook.worksheets.map(x=>x.name),['Bảng lương','Chi tiết tính lương']);const sheet=workbook.getWorksheet('Bảng lương');assert.equal(sheet.getCell('A1').value,'CÔNG TY TNHH THƯƠNG MẠI DỊCH VỤ NGUYỄN HÙNG');assert.equal(sheet.getCell('A2').value,'BẢNG LƯƠNG NHÂN VIÊN');assert.equal(sheet.getCell('A3').value,'THÁNG 08/2026');assert.equal(sheet.views[0].state,'frozen');assert.ok(sheet.autoFilter);assert.equal(sheet.getCell('A8').fill.fgColor.argb,'FF17365D')});
test('summary and total rows use real formulas with matching cached results',async()=>{const workbook=await createPayrollWorkbook(rows,{month:8,year:2026}),sheet=workbook.getWorksheet('Bảng lương'),totalRow=11;assert.equal(sheet.getCell('F6').value.formula,'SUM(F9:F10)');assert.equal(sheet.getCell('F6').value.result,55000000);assert.equal(sheet.getCell(`F${totalRow}`).value.formula,'SUM(F9:F10)');assert.equal(sheet.getCell(`N${totalRow}`).value.result,19400000);assert.equal(sheet.getCell(`O${totalRow}`).value.result,17900000);assert.match(sheet.getCell(`F${totalRow}`).numFmt,/₫/)});
test('xlsx output can be read back by ExcelJS with formulas and no-data case',async()=>{for(const data of [rows,[]]){const source=await createPayrollWorkbook(data,{month:8,year:2026}),buffer=await source.xlsx.writeBuffer(),loaded=new ExcelJS.Workbook();await loaded.xlsx.load(buffer);assert.equal(loaded.worksheets.length,2);assert.equal(loaded.getWorksheet('Bảng lương').getCell('A2').value,'BẢNG LƯƠNG NHÂN VIÊN');const row=9+data.length;assert.ok(loaded.getWorksheet('Bảng lương').getCell(`F${row}`).value.formula)}});
