const service = require('../services/payrollService');
const { createPayrollWorkbook } = require('../services/payrollExcelService');
function fail(res,error){console.error('Payroll:',error);return res.status(error.statusCode||500).json({success:false,message:error.statusCode?error.message:'Không thể xử lý bảng lương lúc này.'});}
function result(res,data,status=200){if(data?.errors)return res.status(422).json({success:false,message:data.errors[0],errors:data.errors});if(data?.notFound)return res.status(404).json({success:false,message:'Không tìm thấy bảng lương.'});return res.status(status).json({success:true,...data});}
async function page(req,res,next){try{return res.render('payroll',{title:'Quản lý bảng lương - NGUYỄN HÙNG',activePage:'payroll',employees:await service.employees()})}catch(e){return next(e)}}
async function list(req,res){try{return result(res,await service.list(req.query))}catch(e){return fail(res,e)}}
async function detail(req,res){try{const payroll=await service.getById(Number(req.params.id));return payroll?result(res,{payroll}):res.status(404).json({success:false,message:'Không tìm thấy bảng lương.'})}catch(e){return fail(res,e)}}
async function generate(req,res){try{const data=await service.generate(Number(req.body.payroll_month),Number(req.body.payroll_year),req.adminAuthorization.id,req.body);return result(res,{...data,message:`Đã tạo ${data.created||0} bảng lương, bỏ qua ${data.skipped||0} bản trùng.`},201)}catch(e){return fail(res,e)}}
async function update(req,res){try{return result(res,{...(await service.updatePayroll(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã cập nhật và tính lại bảng lương.'})}catch(e){return fail(res,e)}}
async function remove(req,res){try{const data=await service.remove(Number(req.params.id),req.adminAuthorization.id,req.body?.deletePassword);return data?result(res,{...data,message:'Đã xóa bảng lương thành công.'}):res.status(404).json({success:false,message:'Không tìm thấy bảng lương.'})}catch(e){if(!String(e.code||'').startsWith('PAYROLL_DELETE_PASSWORD'))console.error('Payroll delete:',e);return res.status(e.statusCode||500).json({success:false,message:e.statusCode?e.message:'Không thể xóa bảng lương.',error:e.code||'PAYROLL_DELETE_FAILED'})}}
async function advance(req,res){try{return result(res,{...(await service.advance(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã lưu tạm ứng.'})}catch(e){return fail(res,e)}}
async function payment(req,res){try{return result(res,{...(await service.payment(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã lưu thanh toán.'})}catch(e){return fail(res,e)}}
async function deduction(req,res){try{return result(res,{...(await service.adjustment(Number(req.params.id),req.body,req.adminAuthorization.id,'deduction')),message:'Đã lưu khoản khấu trừ/phạt.'})}catch(e){return fail(res,e)}}
async function bonus(req,res){try{return result(res,{...(await service.adjustment(Number(req.params.id),req.body,req.adminAuthorization.id,'bonus')),message:'Đã lưu khoản thưởng.'})}catch(e){return fail(res,e)}}
async function penalty(req,res){try{return result(res,{...(await service.penalty(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã ghi nhận phạt theo chính sách phàn nàn.'})}catch(e){return fail(res,e)}}
async function statistics(req,res){try{const data=await service.list({...req.query,page:1,limit:5});return result(res,{stats:data.stats})}catch(e){return fail(res,e)}}
async function lock(req,res){try{const payroll=await service.lock(Number(req.params.id),true,req.adminAuthorization.id);return payroll?result(res,{payroll,message:'Đã khóa bảng lương.'}):res.status(404).json({success:false,message:'Không tìm thấy bảng lương.'})}catch(e){return fail(res,e)}}
async function unlock(req,res){try{const payroll=await service.lock(Number(req.params.id),false,req.adminAuthorization.id);return payroll?result(res,{payroll,message:'Đã mở khóa và ghi lịch sử.'}):res.status(404).json({success:false,message:'Không tìm thấy bảng lương.'})}catch(e){return fail(res,e)}}
async function configuration(req,res){try{return result(res,await service.policies())}catch(e){return fail(res,e)}}
async function updateConfiguration(req,res){try{return result(res,{configuration:await service.updateConfiguration(req.body,req.adminAuthorization.id),message:'Đã cập nhật cấu hình chính sách.'})}catch(e){return fail(res,e)}}
async function yearEndBonus(req,res){try{return result(res,{...(await service.yearEndBonus(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã lưu thưởng cuối năm riêng, không cộng vào lương tháng.'})}catch(e){return fail(res,e)}}
async function salaryIncrease(req,res){try{return result(res,{...(await service.salaryIncrease(Number(req.params.employeeId),req.body,req.adminAuthorization.id)),message:'Đã lưu lịch sử và cập nhật lương từ ngày hiệu lực.'})}catch(e){return fail(res,e)}}
async function revenue(req,res){try{return result(res,await service.revenue(Number(req.params.id)))}catch(e){return fail(res,e)}}
async function revenueDetails(req,res){try{return result(res,await service.revenueDetails(Number(req.params.id)))}catch(e){return fail(res,e)}}
async function manualRevenue(req,res){try{return result(res,{...(await service.saveManualRevenue(Number(req.params.id),req.body,req.adminAuthorization.id)),message:'Đã lưu doanh thu thủ công và tính lại bảng lương.'})}catch(e){return fail(res,e)}}
async function syncRevenue(req,res){try{return result(res,{...(await service.syncRevenue(Number(req.params.id),req.adminAuthorization.id)),message:'Đã đồng bộ doanh thu hệ thống và tính lại bảng lương.'})}catch(e){return fail(res,e)}}
async function productivity(req,res){try{return result(res,await service.productivity(Number(req.params.id)))}catch(e){return fail(res,e)}}
function xml(v){return String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]))}
async function exportExcel(req,res){try{const r=await service.list({...req.query,page:1,limit:5000}),headers=['Mã NV','Họ tên','Loại nhân viên','Doanh thu','Mức năng suất','Lương cơ bản','Phụ cấp','Thưởng','Phạt/Khấu trừ','Tạm ứng','Đã thanh toán','Còn phải trả','Trạng thái'];const rows=r.data.map(x=>[x.employee_code,x.employee_name,x.job_grade==='technician'?'Bậc thợ':'Phụ điện lạnh',x.revenue_amount,x.productivity_salary,x.base_salary,x.allowance,x.bonus,x.deduction,x.advance_total,x.paid_total,x.balance_due,x.status]);rows.push(['','','TỔNG','','','',r.data.reduce((s,x)=>s+Number(x.allowance),0),r.data.reduce((s,x)=>s+Number(x.bonus),0),r.data.reduce((s,x)=>s+Number(x.deduction),0),r.stats.advance_total,r.stats.paid_total,r.stats.balance_total,'']);const cell=v=>`<Cell><Data ss:Type="${typeof v==='number'?'Number':'String'}">${xml(v)}</Data></Cell>`,content=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Bang luong"><Table>${[headers,...rows].map(row=>`<Row>${row.map(cell).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;res.setHeader('Content-Type','application/vnd.ms-excel; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="bang-luong-${req.query.month||'tat-ca'}-${req.query.year||'tat-ca'}.xls"`);return res.send(Buffer.from(`\ufeff${content}`,'utf8'))}catch(e){return fail(res,e)}}
async function exportProfessionalExcel(req,res){try{const month=Number(req.query.month)||null,year=Number(req.query.year)||null,data=await service.list({...req.query,month:month||'',year:year||'',page:1,limit:5000}),workbook=await createPayrollWorkbook(data.data,{month,year}),buffer=await workbook.xlsx.writeBuffer(),filename=`bang-luong-${month||'tat-ca'}-${year||'tat-ca'}.xlsx`;res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${filename}"`);res.setHeader('Content-Length',buffer.length);return res.send(Buffer.from(buffer))}catch(e){return fail(res,e)}}
module.exports={page,list,detail,generate,update,remove,advance,payment,deduction,penalty,bonus,statistics,lock,unlock,configuration,updateConfiguration,yearEndBonus,salaryIncrease,exportExcel:exportProfessionalExcel,revenue,revenueDetails,manualRevenue,syncRevenue,productivity};
